services:
  api:
    build: 
      dockerfile: ./docker/Dockerfile.api
    volumes:
      - "${PWD}:/app"
    entrypoint: pnpm run api:dev
    environment:
      - PORT=4000
      - DATABASE_CONFIG=development
      # - DATABASE_URI=postgres://postgres:password@auth-database:5432/auth_database
    ports:
      - "4000:4000"
